#!/bin/bash




        Sudo yum update
        Sudo yum full-upgrade -y
        Sudo yum dist-upgrade -y
        Bincnt=$(ls -1 /usr/bin | wc -l)
        

	#sudo  ‘LANG=”en_US.UTF-8”
	#LC_MESSAGES=”C”
	#LC_ALL=”en_US.UTF-8”’ >> /etc/environment

	‘LANG=”en_US.UTF-8”’
	#LC_MESSAGES=”C”
	#LC_ALL=”en_US.UTF-8”’ | sudo tee -a /etc/environment

	“After reboot, use ‘locale’ to check”
	Sudo cp -r /etc/ssh/sshd_config /etc/ssh/sshd_config.bak_original
}


Dx_pkg() {
	
	 ‘INSTALLING REQUIRED PACKAGES’
	 2s
	Sudo yum install toilet -y
	Sudo yum install fail2ban unattended-upgrades ufw python3 python3-pip -y 
	Sudo yum install ufw tmux git curl zsh ncdu -y 
	Sudo yum install libvirt-daemon libvirt-daemon-config-network libvirt-daemon-driver-vbox -y 
	Sudo yum install -y qemu-kvm libvirt-daemon-system
        Sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        Sudo yum install ./google-chrome-stable_current_amd64.deb
        Sudo systemctl enable –now libvirtd
        Sudo yum install cockpit-ws cockpit-tests cockpit-system cockpit-storaged cockpit-pcp cockpit-packagekit cockpit-networkmanager cockpit-machines cockpit-bridge cockpit-389-ds cockpit -y 
        
	 2s 
	Sudo yum install tasksel -y 
	Sudo yum install autoconf-archive wget -y
        Sudo yum install sddm 
	Sudo yum install kde-full 
	Sudo yum install plasma-workspace-wayland 
         ‘DONE’;
	 2s 
	Sudo systemctl set-default graphical.target 
	
}

Dx_ufw() {
	
	Sudo ufw allow OpenSSH
	Sudo ufw allow http
	Sudo ufw allow https
	Sudo ufw default allow outgoing

}

Dx_opr() {
	Sudo useradd -m opr;
        Sudo yum install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils ovmf
        Sudo adduser john libvirt
        Sudo adduser john kvm
        Sudo mkdir -vp /var/lib/libvirt/images/hassos-vm  cd /var/lib/libvirt/images/hassos-vm
        Sudo wget https://github.com/home-assistant/operating-system/releases/download/6.6/haos_ova
        Sudo virsh pool-create-as –name hassos –type dir –target /var/lib/libvirt/images/hassos-vm
        Sudo mkdir -vp /var/lib/libvirt/images/hassos-vm  cd /var/lib/libvirt/images/hassos-vm
        Sudo wget https://github.com/home-assistant/operating-system/releases/download/6.6/haos_ova
	Sudo usermod -aG sudo opr;
	Sudo mkdir /home/opr/.ssh 
	Sudo chmod 700 /home/opr/.ssh 
        If [ ! -f /home/opr/.ssh/authorized_keys ];
	Then
		Touch /home/opr/.ssh/authorized_keys;
	Fi

	Sudo chmod -R 700 /home/opr/.ssh
	Sudo chmod 644 /home/opr/.ssh/authorized_keys
	Sudo chown -R opr:opr /home/opr;
	 
	 2s;
         ‘INSTALLING DOCKER’
	Curl -fsSL https://get.docker.com -o get-docker.sh
	Sudo sh get-docker.sh 
	 2s 
	
}

Dx_services() {
	Touch ./.stmp

	  fail2ban >> ./.stmp
	  docker >> ./.stmp
	 ‘cockpit.socket’ >> ./.stmp

	While read -r sline; do
		Sudo systemctl enable “$sline” 
		Sudo systemctl start “$sline” 
		Sudo systemctl status “$sline”;
		 ‘SERVICE ENABLED: ‘ “$sline”
		;
	Done < ./.stmp

	;
	Sudo ufw enable 
	Sudo ufw status;
	 1s 
	;
	Sudo service ssh restart 

}

Dx_netdata() {
	

Dx_update 
Dx_locale 
Dx_pkg 
Dx_ufw 
Dx_opr 
Dx_services 
Sudo dx_netdata;
 
 3s
Toilet ‘fuck you johnny’

	``
